# This workflow will get KoboToolbox to sync once a week. 

name: Kobo Data Sync

on:
  # This schedules the code to run every Tuesday at 2 AM UTC
  schedule: 
    - cron: '0 2 * * 2'  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        pip install supabase python-dotenv koboextractor requests
    
    - name: Execute notebook
      env:
        KOBO_API_KEY: ${{ secrets.KOBO_API_KEY }}
        KOBO_FORM_ID: ${{ secrets.KOBO_FORM_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      run: |
        jupyter nbconvert --to notebook --execute --inplace main.ipynb
    
    - name: Upload execution logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: notebook-execution-${{ github.run_number }}
        path: main.ipynb
        retention-days: 30
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "Notebook execution failed! Check the logs."
        # Optionally add email/Slack notification here
